name: Build

on:
  pull_request:
  push:
    branches:
      - trunk
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: matrix.os
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew build
      - uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          name: string-res-exporter-binary.jar
          path: build/libs/string-res-exporter-*-binary.jar
          if-no-files-found: error
